### ISSUE TITLE
cannot find symbol variable PACKAGE_NAME

### ISSUE THREAD

**Issue by huzzi** [Michenux/YourAppIdea#15]
I'm getting Error:(19, 24) error: cannot find symbol variable PACKAGE_NAME when I build it using Android Studio (1.0.2). Where do I define it? This error is coming from multiple files.

Please help.

**Comment by Michenux** [comment]
Try to replace PACKAGE_NAME with PACKAGE_ID

**Comment by huzzi** [comment]
Hi Michenux,

Thank you for your quick response, I've replaced PACKAGE_NAME with PACKAGE_ID in the following files:
CityContentProvider.java
PlaceContentProvider.java
TutorialContentProvider.java
FriendContentProvider.java

But I'm still getting cannot find symbol variable PACKAGE_ID.

Could you tell me which files I need to update please? sorry i'm new to android programming.

Thanks again in advance for your help.

**Comment by huzzi** [comment]
APPLICATION_ID worked fine.

Thanks.
