### ISSUE TITLE
JDK Error

### ISSUE THREAD

**Issue by naumanahmed19** [Michenux/YourAppIdea#16]
Hi, I have recently found your app and it looks great as I have seen demo.
I am facing issue when I run it on android studio although its not app issue but I am newbie to android.

<pre>
Error:FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':YourAppIdea:compileDebugJavaWithJavac'.
> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':YourAppIdea:compileRetrolambdaDebug'.
> Directory '/Users/sohailahmad/Downloads/YourAppIdea-master/YourAppIdea/build/retrolambda/debug' specified for property 'inputDir' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

</pre>

**Comment by Michenux** [comment]
You need to install Jdk 8 and set environment variable JAVA8_HOME.

**Comment by naumanahmed19** [comment]
thanks for reply yes i have fixed it and its working great. 

I was using tab in my old application. but now i would like to use these tab with  this bootstrap (YourAppIdea).

I found this tutorial its working great for a simple application but I am getting some issues with this app.
http://www.truiton.com/2015/06/android-tabs-example-fragments-viewpager/

do I have to use nested fragment? 
.

**Comment by naumanahmed19** [comment]
Well I got tabs solution and its working fine.

**Comment by Michenux** [comment]
I would like to set up tabs on the "Airport" screen of the app, and remove the spinner.
Two tabs : Arrivals & Departure.

If you want to contribute to my project, you're welcome.

**Comment by naumanahmed19** [comment]
yes I will love too but I am still trying to learn your code.

**Comment by dilipappectual** [comment]
Hey Michenux, Can you tell me which design pattern have you used in complete demo template projects.

**Comment by hopewise** [comment]
@Michenux I still have this error:

FAILURE: Build completed with 2 failures.

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':YourAppIdea:compileDebugJavaWithJavac'.
> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':YourAppIdea:compileRetrolambdaDebug'.
> Directory '/Users/samir/Documents/projects/app-android/YourAppIdea/build/retrolambda/debug' specified for property 'inputDir' does not exist.

```


Although:

```
$ printenv
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
```


And:

```
$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

So, what do you recommend? I am really interested in using your boilerplate

**Comment by hopewise** [comment]
I found the solution here: https://github.com/evant/gradle-retrolambda/issues/61
