### ISSUE TITLE
friend list (recycle view) not scrolling

### ISSUE THREAD

**Issue by rchincho** [Michenux/YourAppIdea#19]
list/detail fragment - friends list not scrolling to buttom. its fixed height.

changed  android:layout_height="wrap_content" to id-friend_recyclerview.

no luck. Please help

**Comment by Michenux** [comment]
I can't reproduce on my phone.

Please give more information about your phone, android version, ...

**Comment by rchincho** [comment]
its happening in genymotion emulator - google nexus 5 - 5.10 - API22 - 1080x1920
