### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by hopewise** [Michenux/YourAppIdea#23]
Can you please help:

> 07-14 12:48:11.779 21178-21178/org.michenux.yourappidea.debug E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                 Process: org.michenux.yourappidea.debug, PID: 21178
>                                                                                 java.lang.RuntimeException: Unable to get provider org.michenux.yourappidea.tutorial.sync.TutorialContentProvider: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.michenux.drodrolib.MCXApplication
>                                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5558)
>                                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5150)
>                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5090)
>                                                                                     at android.app.ActivityThread.access$1600(ActivityThread.java:177)
>                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
>                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                     at android.os.Looper.loop(Looper.java:145)
>                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5938)
>                                                                                     at java.lang.reflect.Method.invoke(Native Method)
>                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
>                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
>                                                                                  Caused by: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.michenux.drodrolib.MCXApplication
>                                                                                     at org.michenux.drodrolib.db.AbstractContentProvider.onCreate(AbstractContentProvider.java:40)
>                                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1716)
>                                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1685)
>                                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5555)
>                                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5150) 
>                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5090) 
>                                                                                     at android.app.ActivityThread.access$1600(ActivityThread.java:177) 
>                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509) 
>                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                     at android.os.Looper.loop(Looper.java:145) 
>                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5938) 
>                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
>                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
>

**Comment by Michenux** [comment]
It seems to be the same problem as #21

**Comment by hopewise** [comment]
yes
